### ISSUE TITLE
Check for zero probability

### ISSUE THREAD

**Issue by oaa3wf** [JuliaPOMDP/AEMS.jl#2]
Is there any chance we could add a statement to the following effect after lines 192 & 206 in action.jl

`if po == 0`
   `    continue`
 `end`

It may save some time for large statespace pomdp's.

**Comment by zsunberg** [comment]
Seems like a good idea to me. Also @dressel, where are `spi` and `si` being used? They don't seem necessary

**Comment by dressel** [comment]
I can't think of a reason not to do it.

@zsunberg Yeah they seem unnecessary. They might be left over from before discrete belief was reformed and we used actual state indexes. The simpler `for sp in state_list` should work.

@oaa3wf Do you want to make the changes and do a pull request? Otherwise Zach or I will take care of it.

**Comment by oaa3wf** [comment]
Yeah I'll make the changes, I might not get it it till the end of the day though.
